### PR TITLE
Reverse proxy improvement

### PR DESCRIPTION
**Pull request by SuperSandro2000**
### What type of change does this PR introduce?
- [x] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Documentation
- [ ] Not Sure?

### Does this PR introduce breaking changes?
- [ ] Yes
- [ ] No
- [x] maybe, do a proper review please

### List any relevant issue numbers:
#97 

### Description:

I try to use relative urls instead of absolute ones. BTW your linter on every git action is bloody annoying!

### CODE REVIEW

**Comment by louistiti** [comment]
[🔧 [1.0.0-beta.3] Reverse proxy improvement](https://trello.com/c/rDyVxPEK/280-%F0%9F%94%A7-100-beta3-reverse-proxy-improvement)

**Comment by louistiti** [comment]
Hello @SuperSandro2000,

Thanks for contributing! I'll take a look at that soon.

Regarding the linter and Git hooks, this is to keep conventions. I plan to make Leon bigger than what he is now, so the earlier we have conventions, the better 😄

**Comment by SuperSandro2000** [comment]
As I wrote in my mail: I would prefer if the checks are CI side and wouldn't interfere with my git operations.

**Comment by louistiti** [comment]
The code needs to follow conventions at every stage, CI side or not. As long as the conventions are respected there'll have no issue.

I've made the following changes on https://github.com/leon-ai/leon/commit/cdef5f8d1577ccf881bbe70e48c4f011edbf731f:

- The web app uses relative URLs.
- Automatically set `LEON_NODE_ENV` and remove it from the .env files. In that way it is less confusing.
  - `production` is set for builds and `npm start`.
  - `development` is set when `npm run dev:server` or `npm run dev:app`.
- Remove `LEON_WEBAPP_HOST` and `LEON_WEBAPP_PORT` as we actually don't need it.
- Rename `LEON_SERVER_HOST` to `LEON_HOST` and `LEON_SERVER_PORT` to `LEON_PORT`.
- During development, force the web app to use the server host and the `4242` port.
- The docs has been updated accordingly (cf. https://github.com/leon-ai/docs.getleon.ai/commit/02fa693178b0259b7d3883d7cc6a623a61beb1c9).

If you see anything else, don't hesitate.

**Pull request closed without merging**
