### PR TITLE
Leon weather 

### PR DESCRIPTION
**Pull request by gnouf1**
### What type of change does this PR introduce?
- [ ] Bugfix
- [X] Feature
- [ ] Refactor
- [ ] Documentation
- [ ] Not Sure?

### Does this PR introduce breaking changes?
- [ ] Yes
- [X ] No

### Description:
With this package you can ask Leon about the weather in all the cities of the world.
It's not full finish because it's miss test and little things.

### CODE REVIEW

**Comment by louistiti** [comment]
Hello @gnouf1,

Thanks for that PR! I'll take a look at that later.

In the meantime, let me know when you have finished it and do not hesitate to ask any questions.

**Comment by gnouf1** [comment]
Okay, i'm gonna add config file and future weather.
And I just want to say : I take a great pleasure when I work on features for leon :p

**Comment by louistiti** [comment]
I'm happy to see that you enjoy working on new Leon features!

If you have any feedback or see things to improve, do not hesitate to reach me out, I'd love to hear them.

**Comment by gnouf1** [comment]
Okay no problem !
After this features i gonna make other i guess, i have time this month.

For me apart from the JS test it seems good for a version 1.0.0.

**Comment by Imperator26** [comment]
I was writing about the same package. I'd like to point out a few suggestions:
- To me the name of the package sounds a bit redundant, perhaps we could call it simply `weather`;
- English comments would be appreciated;
- Perhaps we could use the Python wrapper for OpenWeatherMap: PyOWM;
- Support for Celsius and Fahrenheit scales;
- Set the api token in the `settings.json` file along with other settings like deciding which temperature scale to use etc.

**Comment by gnouf1** [comment]
English comment are just a little forget from me, sorry :)
And for settings.json I totaly agree with you !

**Comment by gnouf1** [comment]
English commentary are up, config file is also OK, Farenheit and Kelvin are now usuable !

**Comment by louistiti** [comment]
Awesome! :clap: 

It would also be better if your commit messages are in English to ensure that most people understand :relaxed:

**Comment by gnouf1** [comment]
Of course !
Sorry i'm new on github (and python) and I learn how to use it :)
From now on I'll be careful about that :)

**Comment by gnouf1** [comment]
Test up :)

**Comment by gnouf1** [comment]
What are finale steps ? :)

**Comment by louistiti** [comment]
I'll review it later, thanks! :smile: 

In the meantime, feel free to pick up another module you would like to develop or whatever you think is good and open an issue to discuss about it first.

**Comment by gnouf1** [comment]
Little update, now he use multilanguage weather :)

**Comment by gnouf1** [comment]
Merge with other weather package

**Comment by louistiti** [comment]
https://github.com/leon-ai/leon/pull/108.

**Pull request closed without merging**
