### PR TITLE
Adds Italian translation and fixes some spelling errors

### PR DESCRIPTION
**Pull request by Imperator26**
### What type of change does this PR introduce?
- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Documentation
- [ ] Not Sure?

### Does this PR introduce breaking changes?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by louistiti** [comment]
[✨ Languages support](https://trello.com/c/PqiIElyx/217-%E2%9C%A8-languages-support)

**Comment by louistiti** [comment]
Hello @Imperator26,

Awesome work! Thanks for that!

I'll keep this PR pending until we focus on more languages integrations. Because we need to spend some time to implement the Italian voice according to the different providers.

**Comment by louistiti** [comment]
Hello @Imperator26,

Could you please open another PR for your Weather package and keep that one dedicated to the Italian translation? 😃

**Comment by Imperator26** [comment]
> Hello @Imperator26,
> 
> Could you please open another PR for your Weather package and keep that one dedicated to the Italian translation? 😃

Sure, but these fixes were about other packages.

**Comment by louistiti** [comment]
What I mean is your work on your Weather package is getting into that PR too (e.g. https://github.com/leon-ai/leon/pull/94/files#diff-760b575aacb8cc2efd07b87b9ebd2596).

That must completely be part of another PR.

**Comment by Imperator26** [comment]
> What I mean is your work on your Weather package is getting into this PR too (e.g. https://github.com/leon-ai/leon/pull/94/files#diff-760b575aacb8cc2efd07b87b9ebd2596).
> 
> That must completely be part of another PR.

Yeah sorry I realized I messed this PR up.

**Comment by Imperator26** [comment]
@louistiti quick question should I commit changes to `package-lock.json`?

**Comment by louistiti** [comment]
Yes you can but it is not necessary.

**Pull request closed without merging**
