### PR TITLE
HaveIBeenPwned Module

### PR DESCRIPTION
**Pull request by iifeoluwa**
### What type of change does this PR introduce?
- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Documentation
- [ ] Not Sure?

### Does this PR introduce breaking changes?
- [ ] Yes
- [x] No

### List any relevant issue numbers:
#69 
### Description:
This adds the HaveIBeenPwned module to the Checker package.

cc: @louistiti I used Google Translate to translate English expressions/answers to French, I am not sure of the accuracy of the translation so I'd appreciate your help in helping to look that over.

### CODE REVIEW

**Comment by louistiti** [comment]
Hello @iifeoluwa,

Thanks for this PR and this cool new module! 😎 

Let me come back to you once the `1.0.0-beta.2` is released (which means in the coming days).

**Comment by iifeoluwa** [comment]
Great! I'm currently looking through the roadmap for other stuff I can help out with. If you have any suggestions, please let me know.

**Comment by louistiti** [comment]
Hello @iifeoluwa,

Thanks for your work! :tada: 

I've made a few changes to allow us to have several data breaches in one output.

**Comment by louistiti** [comment]
[✨ Checker Package - Have I Been Pwned Module](https://trello.com/c/8zUohuMG/104-%E2%9C%A8-checker-package-have-i-been-pwned-module)

**Pull request merged**
