### PR TITLE
How old module

### PR DESCRIPTION
**Pull request by Lp-Francois**
### What type of change does this PR introduce?
- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Documentation
- [ ] Not Sure?

### Does this PR introduce breaking changes?
- [ ] Yes
- [x] No

### Description:

[Trello card](https://trello.com/c/8Xs4j3Mr/279-%E2%9C%A8-100-beta3-how-old-module-leon-package)

```
Leon, how old are you?
Leon, are you old?
Leon, are you young?
Leon, when have you been created?
```
Give an answer with the related date of the 1.0.0-beta.0 release. We can hard code the date here as it is a fix one.

### CODE REVIEW

**Comment by louistiti** [comment]
Hello @AsterYujano,

Thanks for your contribution! I hope your first experience with Leon went well 😃

For what I see, it is all good. However, could you please add an answer where Leon provide a related date of his age? Such as, "I'm 6 months and 3 days old.".

That would be awesome!

**Comment by AsterYujano** [comment]
I will have a look at it!

**Comment by ThomasRitaine** [comment]
Hello !

Maybe you could add some other answers such as :

#### English
- I am still very young, I am only **%years%** years and **%days%** days old.
- I'm only **%years%** years and **%days%** days old, but I can already talk!
- I am only **%years%** years and **%days%** days old. How does it feel to be older?
- I am surely much younger than you, I am only **%years%** years and **%days%** days old.

#### French
- Je suis encore très jeune, je n'ai que **%years%** ans et **%days%** jours.
- J'ai seulement  **%years%** ans et **%days%** jours, mais je peux déjà parler !
- Je n'ai que  **%years%** ans et **%days%** jours. Qu'est-ce que ça fait d'être plus âgé ?
- Je suis sûrement bien plus jeune que vous, j'ai seulement  **%years%** ans et **%days%** jours.

#### For me, to get better
I am very young on GitHub. Is there a way to put my commit on your pull request ?

**Comment by AsterYujano** [comment]
Hello Thomas, 

Feel free to complete the PR :)

**Review by Divlo — APPROVED** [review]
Thanks for your contributions! @AsterYujano and @ThomasRitaine 

LGTM! :tada:

**Comment by Divlo** [comment]
[✨ [1.0.0-beta.7] How Old Module - Leon Package](https://trello.com/c/8Xs4j3Mr/279-%E2%9C%A8-100-beta7-how-old-module-leon-package)

**Pull request closed without merging**
